config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'world#home'

  resources :world, only: [] do
    collection do
      get 'playground' => 'world#playground'
      post 'start' => 'world#start'
      post 'clear' => 'world#clear'
    end
  end
end

app/models/world.rb
class World
  include OverriddenMethods
  attr_accessor :grid, :grid_size

  def initialize(size)
    @grid_size = size
    @grid = Array.new(grid_size) { Array.new(grid_size, dead) }
  end

  def load(cells)
    cells.each { |x, y| grid[x][y] = born }
  end

  def tick
    @grid = @grid.map.with_index do |column, x|
              column.map.with_index do |cell, y|
                if cell.dead?
                  should_take_birth?(x, y) ? born : dead
                elsif cell.alive?
                  should_live?(x, y) ? lives : dies
                end
              end
            end
  end

  def dead
    0
  end

  def born
    1
  end

  alias dies dead
  alias lives born
  private :dies, :dead, :lives, :born

  private

  def should_take_birth?(x, y)
    count_neighbors([x, y]) == 3
  end

  def should_live?(x, y)
    count_neighbors([x, y]).between?(2, 3)
  end

  def count_neighbors(cell)
    NEIGHBOURS.values.map { |neighbor| cell.zip(neighbor).map { |v| v.reduce(:+) } }.select do |neighbor|
      neighbor = neighbor.map { |n| n.negative? ? (grid_size - born) : n > (grid_size - 1) ? dead : n }
      grid[neighbor.first][neighbor.last].nonzero?
    end.length
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/world_controller.rb
class WorldController < ApplicationController
  include OverriddenMethods
  before_action :set_grid, only: %i[playground start clear]
  before_action :initialize_grid, only: %i[clear playground]
  before_action :set_population, only: %i[playground]

  def home; end

  def clear; end

  def playground
    @grid = @@life.grid
  end

  def start
    @@life.load(game_params[:cells].each_value.map { |arr| arr.map(&:to_i) }) if game_params[:load].true?
    @grid = @@life.tick
  end

  private

  def game_params
    game_params = params.permit(:load)
    game_params[:cells] = params[:cells].as_json
    game_params.permit!
  end

  def set_grid
    @size = GRID_SIZE
  end

  def initialize_grid
    @@life = World.new(@size)
  end

  def set_population
    return unless params[:pattern] && (pattern = PATTERNS[params[:pattern]]).present?
    @@life.load(pattern.map { |arr| arr.map(&:to_i) })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Conway's Game of Life"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/views/layouts/_footer.html.slim
.container style='position:fixed;'
  .navbar.navbar-inverse.navbar-fixed-bottom role="navigation"
    .row
      .group1.col-md-8.col-md-offset-2 style='text-align: center;'
        a href="https://github.com/md-farhan-memon/conways_game_of_life" target="_blank" title="GitHub - Conway's Game of Life"
          img src="/gh.png" height="50" width="50"
        a href="https://in.linkedin.com/in/mdfarhanmemon" target="_blank" title="LinkedIn Profile" 
          img src="/li.png" height="50" width="50"
        a href="https://www.facebook.com/mdfarhan.memon" target="_blank" title="Facebook Profile" 
          img src="/fb.png" height="50" width="50"
        a href="https://stackoverflow.com/users/6548745/md-farhan-memon" target="_blank" title="Stack Overflow Profile"
          img src="/so.png" height="50" width="50"

app/views/layouts/_header.html.slim
nav.navbar.navbar-inverse
  .container-fluid
    .navbar-header
      a.navbar-brand href='/' Conway's Game of Life

app/views/layouts/application.html.slim
doctype html
html
  head
    meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
      title= full_title(yield(:title))
      = stylesheet_link_tag    'normalize', media: 'all', 'data-turbolinks-track': 'reload'
      = stylesheet_link_tag    'animate', media: 'all', 'data-turbolinks-track': 'reload'
      = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
      = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
      = csrf_meta_tags
  body style='text-align:center;padding-bottom: 70px'
    = render partial: 'layouts/header'
    .container
      .row
        .col-lg-8.col-lg-offset-2.col-md-8.col-md-offset-2
          = yield
    = render partial: 'layouts/footer'

app/views/world/_grid.html.slim
.grid
  - for i in 0..(@size - 1)
    .row.row-no-padding
      - for j in 0..(@size - 1)
        .col-lg-1.col-md-1.col-xs-1
          - if  @grid and @grid[i][j] == 1
            .cell.active.fadeIn row="#{i}" col="#{j}"
          - else
            .cell.fadeIn row="#{i}" col="#{j}"

app/views/world/clear.js.slim
| $('.grid').replaceWith('
= escape_javascript(render(partial: "grid", locals: {}))
| ');
| $('#run').text("RUN");

app/views/world/home.html.slim
h1 Conway's Game of Life
.row
  .col-md-12
    h4 Still Lives
    = link_to image_tag('still_block.png', size: '80x80', style: 'margin-left:5px; margin-right:5px', title: 'Block'), playground_world_index_path(pattern: 'still_block')
    = link_to image_tag('still_beehive.png', size: '120x80', style: 'margin-left:5px; margin-right:5px', title: 'Beehive'), playground_world_index_path(pattern: 'still_beehive')
    = link_to image_tag('still_boat.png', size: '100x80', style: 'margin-left:5px; margin-right:5px', title: 'Boat'), playground_world_index_path(pattern: 'still_boat')
    = link_to image_tag('still_loaf.png', size: '120x80', style: 'margin-left:5px; margin-right:5px', title: 'Loaf'), playground_world_index_path(pattern: 'still_loaf')
    = link_to image_tag('still_tub.png', size: '100x80', style: 'margin-left:5px; margin-right:5px', title: 'Tub'), playground_world_index_path(pattern: 'still_tub')
.row
  .col-md-12
    h4 Oscillating Lives
    = link_to image_tag('osc_blinker.gif', size: '80x80', style: 'margin-left:5px; margin-right:5px', title: 'Blinker'), playground_world_index_path(pattern: 'osc_blinker')
    = link_to image_tag('osc_beacon.gif', size: '120x80', style: 'margin-left:5px; margin-right:5px', title: 'Beacon'), playground_world_index_path(pattern: 'osc_beacon')
    = link_to image_tag('osc_toad.gif', size: '120x80', style: 'margin-left:5px; margin-right:5px', title: 'Toad'), playground_world_index_path(pattern: 'osc_toad')
.row
  .col-md-12
    h4 Spaceship Lives
    = link_to image_tag('GSS.gif', size: '80x80', style: 'margin-left:5px; margin-right:5px', title: 'Blinker'), playground_world_index_path(pattern: 'GSS')
    = link_to image_tag('LWSS.gif', size: '120x80', style: 'margin-left:5px; margin-right:5px', title: 'Beacon'), playground_world_index_path(pattern: 'LWSS')
.row
  .col-md-12
    h4 Experiment Yourself
    = link_to image_tag('blank.png', size: '80x80', style: 'margin-left:5px; margin-right:5px', title: 'Blank'), playground_world_index_path

app/views/world/index.html.slim
.clear
  i.fa.fa-times.fa-2x
  
.game-wrapper
  .game
    = render partial: 'grid'

  .row
    .col-md-6.col-md-offset-3
      a#run.btn.btn-block.disabled Run

app/views/world/playground.html.slim
- provide(:title, params[:pattern].to_s.titleize)
.clear
  i.fa.fa-times.fa-2x
  
.game-wrapper
  .game
    = render partial: 'grid'

  .row
    .col-md-6.col-md-offset-3
      a#run.btn.btn-block Run

app/views/world/start.js.slim
| $('.grid').replaceWith('
= escape_javascript(render(partial: "grid", locals: {}))
| ');